# Generated by Django 5.2.17 on 2026-09-25 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_itempedido_id_variante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('texto_boton', models.CharField(max_length=100)),
                ('imagen_principal', models.TextField(blank=True)),
                ('secciones', models.JSONField(blank=True, default=dict)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_landing', to='core.tienda')),
            ],
            options={
                'db_table': 'configuracion_landing',
            },
        ),
    ]
