# Generated by Django 5.2.17 on 2026-09-25 22:44

import apps.landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlanding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/logos/', validators=[apps.landing.models.validate_store_logo]),
        ),
        migrations.AlterField(
            model_name='configuracionlanding',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/', validators=[apps.landing.models.validate_landing_image]),
        ),
    ]
