import {useState} from 'react';
import {useAdmin} from '../context/AdminContext';
import {AdminCard,Alert,Input,Select,Toggle,Button} from '../components/ui';
import type {AdminConfig} from '../types';
export default function Authentication(){const {config,setConfig}=useAdmin();const [form,setForm]=useState(config.authenticationConfiguration);const [rule,setRule]=useState(config.requiresAuth);const [saved,setSaved]=useState(false);const [error,setError]=useState('');
 const update=(change:Partial<typeof form>)=>{setForm({...form,...change});setSaved(false);};
 function save(){if((!form.emailPassword&&!form.google&&(!form.guestCheckout||rule==='required'))){setError('Activa un método de acceso compatible con la regla de compra.');return;}setSaved(setConfig({...config,authenticationConfiguration:form,requiresAuth:rule}));setError('');}
 return <form className="flex flex-col gap-5 max-w-2xl" onSubmit={e=>{e.preventDefault();save();}}><Alert variant="info" title="Acceso de clientes">Define las alternativas visibles al iniciar sesión. Esta configuración demo se conectará más adelante; Google no realiza autenticación real.</Alert><AdminCard className="flex flex-col gap-5"><div><h2 className="font-semibold text-sm">Métodos de acceso</h2><p className="text-xs text-[var(--muted-foreground)] mt-1">Activa al menos una alternativa para que tus compradores puedan continuar.</p></div><Toggle checked={form.emailPassword} onChange={emailPassword=>update({emailPassword})} label="Correo electrónico y contraseña"/><div className="border-t border-[var(--border)] pt-4 grid gap-3"><Toggle checked={form.google} onChange={google=>update({google})} label="Continuar con Google"/>{form.google&&<Input label="Google OAuth Client ID" value={form.googleClientId} onChange={e=>update({googleClientId:e.target.value})} placeholder="xxxx.apps.googleusercontent.com" hint="En este prototipo se conserva como configuración visual."/>}</div><div className="border-t border-[var(--border)] pt-4 grid gap-3"><Toggle checked={form.guestCheckout} onChange={guestCheckout=>update({guestCheckout})} label="Permitir continuar como invitado"/><Select label="Regla para comprar" value={rule} onChange={e=>{setRule(e.target.value as AdminConfig['requiresAuth']);setSaved(false);}} options={[{value:'none',label:'No solicitar cuenta'},{value:'optional',label:'Cuenta opcional'},{value:'required',label:'Cuenta obligatoria antes de pagar'}]}/></div></AdminCard>{error&&<Alert variant="error">{error}</Alert>}{saved&&<Alert variant="success">Configuración de autenticación guardada.</Alert>}<Button type="submit">Guardar autenticación</Button></form>;
}
