# Generated by Django 5.2.17 on 2026-09-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id_variante', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('atributos', models.JSONField(default=dict, help_text="Ejemplo: {'color': 'Negro', 'talla': 'M'}")),
                ('es_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='core.producto')),
            ],
            options={
                'db_table': 'variante_producto',
                'constraints': [models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='chk_variante_precio_valido'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='chk_variante_stock_valido')],
            },
        ),
    ]
