# Generated by Django 5.2.17 on 2026-09-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_varianteproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='id_variante',
            field=models.ForeignKey(blank=True, db_column='id_variante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='core.varianteproducto'),
        ),
    ]
