# Generated by Django 5.2.17 on 2026-10-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_pago',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id_variante', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('atributos', models.JSONField(default=dict)),
                ('es_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'variante_producto',
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo_contacto',
            field=models.EmailField(default='', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_contacto',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('id_usuario__isnull', False), models.Q(('correo_contacto', ''), _negated=True), _connector='OR'), name='chk_pedido_tiene_comprador'),
        ),
        migrations.AddField(
            model_name='configuracionpago',
            name='tienda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_pago', to='core.tienda'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='chk_variante_precio_valido'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='chk_variante_stock_valido'),
        ),
    ]
