# Generated by Django 5.2.17 on 2026-10-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTransbank',
            fields=[
                ('id_configuracion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_comercio', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=255)),
                ('ambiente', models.CharField(choices=[('INTEGRACION', 'Integración'), ('PRODUCCION', 'Producción')], default='INTEGRACION', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_tienda', models.OneToOneField(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_transbank', to='core.tienda')),
            ],
            options={
                'db_table': 'configuracion_transbank',
            },
        ),
    ]
