# Generated by Django 5.2.17 on 2026-10-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracionpaypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMercadoPago',
            fields=[
                ('id_tienda', models.OneToOneField(db_column='id_tienda', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configuracion_mercadopago', serialize=False, to='core.tienda')),
                ('public_key', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.CharField(blank=True, default='', max_length=255)),
                ('ambiente', models.CharField(choices=[('SANDBOX', 'Sandbox (Pruebas)'), ('PRODUCCION', 'Producción (Real)')], default='SANDBOX', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Mercado Pago',
                'verbose_name_plural': 'Configuraciones Mercado Pago',
                'db_table': 'configuracion_mercadopago',
            },
        ),
    ]
