# Generated by Django 5.2.17 on 2026-10-03 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracionpago_varianteproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='atributos_variante',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nombre_producto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto_mongo_id',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='itempedido',
                    name='sku',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='pedido',
            name='clave_checkout',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='contacto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedido',
            name='huella_checkout',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tienda'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]