# Generated by Django 5.2.17 on 2026-10-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracionpago_varianteproducto_and_more'),
        ('core', '0011_checkout_order_snapshots'),
    ]

    operations = [
    ]
