# Generated by Django 5.2.17 on 2026-10-03 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20261003_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='chk_pedido_tiene_comprador',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='atributos',
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('id_usuario__isnull', False), models.Q(('correo_contacto', ''), _negated=True), ('comprador__isnull', False), models.Q(('contacto', {}), _negated=True), _connector='OR'), name='chk_pedido_tiene_comprador'),
        ),
    ]
