# Generated by Django 5.2.17 on 2026-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_pedido_chk_pedido_tiene_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
