# Generated by Django 5.2.17 on 2026-10-04 03:40

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemcarrito_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='identificador',
            field=models.CharField(default=apps.core.models.generar_identificador_orden, editable=False, max_length=20, null=True, verbose_name='Número de Orden'),
        ),
    ]
