# Generated by Django 5.2.17 on 2026-10-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cifrar_credenciales_pago'),
        ('core', '0016_pedido_identificador'),
    ]

    operations = [
    ]
