# Generated by Django 5.2.7 on 2026-10-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20261004_0731"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tienda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_entrega",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "db_table": "configuracion_entrega",
            },
        ),
    ]
