# Generated by Django 5.2.17 on 2026-10-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracionpago_varianteproducto'),
        ('core', '0018_configuracionentrega'),
    ]

    operations = [
    ]
