# Generated by Django 5.2.7 on 2026-09-25 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_itempedido_id_variante"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plantilla_seleccionada",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("editorial", "Editorial"),
                            ("minimal", "Minimal"),
                            ("visual", "Visual"),
                            ("catalog", "Catalog"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("personalizacion", models.JSONField(blank=True, default=dict)),
                (
                    "tienda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_visual",
                        to="core.tienda",
                    ),
                ),
            ],
            options={
                "db_table": "configuracion_visual",
            },
        ),
    ]
