# Generated by Django 5.2.7 on 2026-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visual_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionvisual",
            name="logo_negocio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
