# Generated by Django 5.2.17 on 2026-10-01 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_producto_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAutenticacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_password', models.BooleanField(default=True)),
                ('google', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('guest_checkout', models.BooleanField(default=True)),
                ('requires_auth', models.CharField(choices=[('none', 'No solicitar cuenta'), ('optional', 'Cuenta opcional'), ('required', 'Cuenta obligatoria antes de pagar')], default='optional', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_autenticacion', to='core.tienda')),
            ],
            options={
                'db_table': 'configuracion_autenticacion',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
