import {useState} from 'react';
import {Link, NavLink, useLocation} from 'react-router-dom';
import {menuItems,legalSlugs,templatePaths} from '../../config/navigation';
import {legalPageTemplates} from '../../data/mockAdminData';
import {useAdmin} from '../../context/AdminContext';
import {Icon,InstitutionalBadge} from '../ui';
export function AdminSidebar({open,onClose}:{open:boolean;onClose:()=>void}) {
  const {config}=useAdmin(); const {pathname}=useLocation(); const [legalOpen,setLegalOpen]=useState(true);
  return <>{open&&<button className="fixed inset-0 bg-black/40 z-30 md:hidden" aria-label="Cerrar navegación" onClick={onClose}/>}<aside id="admin-sidebar" className={'admin-sidebar '+(open?'is-open':'')}><div className="p-5 border-b border-[var(--border)] flex items-center justify-between gap-2"><div className="min-w-0"><h2 className="font-bold truncate">{config.name}</h2><p className="text-xs text-[var(--muted-foreground)]">Emprendedor</p></div><Link to={templatePaths[config.template]} className="shrink-0 text-xs font-semibold text-[var(--primary)] bg-[var(--secondary)] px-2.5 py-1.5 rounded-lg flex items-center gap-1"><Icon name="bag" className="w-3.5 h-3.5"/>Ver tienda</Link></div><nav aria-label="Panel del emprendedor" className="p-3 space-y-1 flex-1 overflow-y-auto">{menuItems.map(item=><NavLink key={item.path} to={item.path} end={item.path==='/emprendedor'} onClick={onClose} className={({isActive})=>'admin-nav-link '+(isActive?'active':'')}><Icon name={item.icon}/>{item.label}</NavLink>)}<button type="button" onClick={()=>setLegalOpen(!legalOpen)} aria-expanded={legalOpen} className={'admin-nav-link w-full '+(pathname.includes('/legal/')?'active':'')}><Icon name="file"/><span className="flex-1 text-left">Páginas legales</span><span>{legalOpen?'⌃':'⌄'}</span></button>{legalOpen&&<div className="ml-7 pl-2 border-l border-[var(--border)] grid gap-1">{(Object.keys(legalSlugs) as (keyof typeof legalSlugs)[]).map(type=><NavLink key={type} to={'/emprendedor/legal/'+legalSlugs[type]} onClick={onClose} className={({isActive})=>'px-2 py-2 text-xs rounded-lg '+(isActive?'bg-[var(--secondary)] text-[var(--primary)] font-semibold':'text-[var(--muted-foreground)]')}>{legalPageTemplates[type].title}</NavLink>)}</div>}</nav><div className="p-4 border-t border-[var(--border)]"><InstitutionalBadge compact/></div></aside></>;
}
