// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXP7-CyMma6g7NmgNlsimnNxEXEKqf_Tk',
    appId: '1:662279003599:web:1ec41d5f4abd3d84e706ba',
    messagingSenderId: '662279003599',
    projectId: 'app-cotizaciones-b25ac',
    authDomain: 'app-cotizaciones-b25ac.firebaseapp.com',
    storageBucket: 'app-cotizaciones-b25ac.firebasestorage.app',
    measurementId: 'G-X3W6SWQCTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSvuzFCYsSC5FSWhm_mMoAPbitj9Nhavc',
    appId: '1:662279003599:android:d405ea3af8ef960ce706ba',
    messagingSenderId: '662279003599',
    projectId: 'app-cotizaciones-b25ac',
    storageBucket: 'app-cotizaciones-b25ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4ZfZniO2AR_ViGp2TNgTXDb8ajRjtMY',
    appId: '1:662279003599:ios:fe4e010ddee95212e706ba',
    messagingSenderId: '662279003599',
    projectId: 'app-cotizaciones-b25ac',
    storageBucket: 'app-cotizaciones-b25ac.firebasestorage.app',
    iosBundleId: 'com.example.desarrolloMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx4ZfZniO2AR_ViGp2TNgTXDb8ajRjtMY',
    appId: '1:662279003599:ios:fe4e010ddee95212e706ba',
    messagingSenderId: '662279003599',
    projectId: 'app-cotizaciones-b25ac',
    storageBucket: 'app-cotizaciones-b25ac.firebasestorage.app',
    iosBundleId: 'com.example.desarrolloMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXP7-CyMma6g7NmgNlsimnNxEXEKqf_Tk',
    appId: '1:662279003599:web:01dd11d99013b1c3e706ba',
    messagingSenderId: '662279003599',
    projectId: 'app-cotizaciones-b25ac',
    authDomain: 'app-cotizaciones-b25ac.firebaseapp.com',
    storageBucket: 'app-cotizaciones-b25ac.firebasestorage.app',
    measurementId: 'G-K5DT72XVCY',
  );
}
